### ISSUE TITLE
Return error message when gene not found

### ISSUE THREAD

**Issue by hilldr** [hilldr/gene_retriever#11]
'gene retriever' should return an informative error message when a user-specified gene is not found

**Comment by sthodla** [comment]
Current version of the function already does this, though it doesn't say that a gene was not found but rather says there is an error in the code and will print the same general error message. We place this error message in the README document, so that users know what is wrong when presented with this error.

**Comment by hilldr** [comment]
See 'Gene not found, function fails' Issue #14
